config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'

  resources :posts do
    resources :mark
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :post
  validates :points, presence: true, numericality: {more_than_or_equal_to: 0, less_than_or_equal_to: 100,  only_integer: true }

  before_save :set_letter
  private def set_letter
    case self.points
    when 0..29
      self.letter ||= 'F'
    when 30..59
      self.letter ||= 'D'
    when 60..74
      self.letter ||= 'C'
    when 75..90
      self.letter ||= 'B'
    when 91..100
      self.letter ||= 'A'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :marks
  validates :title, presence: true, length: {minimum:5, maximum: 250}
  validates :description, presence: true, length: {minimum:5, maximum: 500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mark_controller.rb
class MarkController < ApplicationController
  def create
    @Report = Report.find(params[:Report_id])
    @mark = @Report.marks.create(mark_params)
    redirect_to Report_path(@Report)
  end

  def destroy
    @Report = Report.find(params[:Report_id])
    @mark = @Report.marks.find(params[:id])
    @mark.destroy
    redirect_to Report_path(@Report)
  end

  private def mark_params
      params.require(:mark).permit(:points)
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  def create
    @Report = Report.find(params[:Report_id])
    @mark = @Report.marks.create(mark_params)
    redirect_to Report_path(@Report)
  end

  def destroy
    @Report = Report.find(params[:Report_id])
    @mark = @Report.marks.find(params[:id])
    @mark.destroy
    redirect_to Report_path(@Report)
  end

  private def mark_params
      params.require(:mark).permit(:points)
  end
end

app/controllers/post_controller.rb
class ReportsController < ApplicationController
  def index
    @Report = Report.all
  end

  def new
    @Report = Report.new
  end

  def edit
    @Report = Report.find(params[:id])
  end

  def update
    @Report = Report.find(params[:id])

    if(@Report.update(Report_params))
      redirect_to @Report
    else
      render 'edit'
    end
  end

  def destroy
    @Report = Report.find(params[:id])

    @Report.destroy
    redirect_to :action => :index
  end

  def show
    @Report = Report.find(params[:id])
  end

  def create
    @Report = Report.new(Report_params)

    if(@Report.save)
      redirect_to @Report
    else
      render 'new'
    end
  end

  private def Report_params
    params.require(:Report).permit(:title, :description)
  end
end

app/controllers/posts_controller.rb
class ReportsController < ApplicationController
  def index
    @Report = Report.all
  end

  def new
    @Report = Report.new
  end

  def edit
    @Report = Report.find(params[:id])
  end

  def update
    @Report = Report.find(params[:id])

    if(@Report.update(Report_params))
      redirect_to @Report
    else
      render 'edit'
    end
  end

  def destroy
    @Report = Report.find(params[:id])

    @Report.destroy
    redirect_to :action => :index
  end

  def show
    @Report = Report.find(params[:id])
  end

  def create
    @Report = Report.new(Report_params)

    if(@Report.save)
      redirect_to @Report
    else
      render 'new'
    end
  end

  private def Report_params
    params.require(:Report).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mark_helper.rb
module MarkHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>lab6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto"><%= link_to "All reports", home_path %></h5>
      <span class="btn btn-outline-primary"><%= link_to "New report", new_post_path %></span>
    </div>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/edit.html.erb
<h2>Edit report</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="profiler-button-active"> <%= msg %> </div>
    <% end %>
  <% end %>
  <p>
    Title<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Description<br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-dark'}) %>
  </p>
<% end %>

app/views/posts/index.html.erb
<% @post.each do |post| %>
  <div class="alert">
    <h3><%= post.title %></h3>
    <p><%= post.description %></p>
    <%= link_to "View", post_path(post), :class => "btn btn-primary" %>
  </div>

<% end %>

app/views/posts/new.html.erb
<h2>Add report</h2>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"> <%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Title
    <br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Description<br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-link'}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.description %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-light' %>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger' %>
<hr>
<h3>Mark</h3>
<% @post.marks.each do |mark| %>
  <div class="alert alert-ligth">
    <p><%= mark.points %>(<%= mark.letter %>)</p>
    <%= link_to "Delete", [mark.post, mark], method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger' %>
  </div>
<% end %>
<hr>
<h3>New mark</h3>
<%= form_for([@post, @post.marks.build]) do |f| %>
    <p><br>
    <%= f.text_field(:points, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit("Оценка", {:class => 'btn btn-success'}) %>
  </p>
<% end %>